import { useEffect, useRef, useState } from 'react';
import { lessonWords, words } from '../../data/lesson';
import { useLearningStore } from '../../store/useLearningStore';
import { canPlaceSpellingPart, calculateMatchScore } from './vocabularyLogic';
import './vocabulary.css';
import './spellingDrag.css';

const tabs = [{ id: 'overview', label: '课课清' }, { id: 'spelling', label: '拼写大师' }, { id: 'review', label: '滚动复习' }, { id: 'match', label: '词汇大闯关' }];
const overviewWords = ['eight', 'nine', 'ten', 'zero', 'many', 'peach', 'lemon', 'watermelon', 'strawberry', 'cherry', 'home', 'school', 'zoo', 'shop', 'supermarket', 'jacket', 'boots', 'coat', 'dress', 'skirt'];
export const playLessonAudio = (audioPath) => { const audio = new Audio(audioPath); void audio.play(); };

function VocabularyOverview({ reviewMode, onModeChange, onChallenge }) {
  const [selected, setSelected] = useState(0); const current = lessonWords[selected];
  return <section className="vocab-overview lesson-clear"><div className="overview-stats"><span>（用户名）</span><span>学习时长：50 min</span><span>积分：120</span><span>积分商城</span></div><div className="overview-tabs"><button className={!reviewMode ? 'active' : ''} onClick={() => onModeChange(false)}>课课清</button><button className={reviewMode ? 'active' : ''} onClick={() => onModeChange(true)}>滚动复习</button></div>{reviewMode ? <div className="rolling-grid">{overviewWords.map((item) => <button className="overview-word" key={item}>{item}</button>)}</div> : <div className="lesson-board"><aside className="lesson-word-list">{lessonWords.map((item, index) => <button className={selected === index ? 'selected' : ''} onClick={() => setSelected(index)} key={item.word}>{item.word}</button>)}<button className="challenge-button" onClick={onChallenge}>拼写大师</button></aside><article className="lesson-detail"><div className="detail-copy"><h2>{current.word}</h2><button className="detail-audio" aria-label="播放单词发音" onClick={() => playLessonAudio(current.audio)}>🔊</button><span className="detail-phonetic">{current.phonetic}</span><p>{current.meaning}</p><div className="detail-spelling">{current.word.split('').map((letter, index) => <span key={`${letter}-${index}`}>{letter}</span>)}</div><p className="detail-sentence">{current.sentence}</p></div><div className="detail-visual"><img src={current.image} alt={current.word} /><div className="star-rating"><span>🎙️</span>{[1, 2, 3, 4, 5].map((star) => <button key={star} aria-label={`${star} 星`}>☆</button>)}</div></div><button className="detail-arrow prev" onClick={() => setSelected((selected + lessonWords.length - 1) % lessonWords.length)}>‹</button><button className="detail-arrow next" onClick={() => setSelected((selected + 1) % lessonWords.length)}>›</button></article></div>}</section>;
}

function SpellingGame() {
  const setScore = useLearningStore((state) => state.setSpellingScore); const [wordIndex, setWordIndex] = useState(0); const [placed, setPlaced] = useState([]); const [draggedIndex, setDraggedIndex] = useState(null); const [dropTarget, setDropTarget] = useState(null); const [message, setMessage] = useState(''); const advanceTimer = useRef(null); const word = words[wordIndex];
  const playSpellingAudio = () => { const audio = new Audio(word.audio); void audio.play(); };
  const playEffect = (audioPath) => { const audio = new Audio(audioPath); void audio.play(); };
  const reset = () => { window.clearTimeout(advanceTimer.current); setPlaced([]); setDraggedIndex(null); setDropTarget(null); setMessage(''); };
  const next = () => { setWordIndex((i) => (i + 1) % words.length); reset(); };
  useEffect(() => () => window.clearTimeout(advanceTimer.current), []);
  const handleDragStart = (event, partIndex) => { event.dataTransfer.setData('text/plain', String(partIndex)); event.dataTransfer.effectAllowed = 'move'; setDraggedIndex(partIndex); };
  const handleDrop = (event, targetIndex) => { event.preventDefault(); const partIndex = Number(event.dataTransfer.getData('text/plain') || draggedIndex); setDropTarget(null); setDraggedIndex(null); if (placed[targetIndex]) return; if (!canPlaceSpellingPart(partIndex, targetIndex, word.spelling)) { playEffect('/music/失败.mp3'); return; } const nextPlaced = [...placed]; nextPlaced[targetIndex] = word.spelling[partIndex]; setPlaced(nextPlaced); if (nextPlaced.length === word.spelling.length && nextPlaced.every(Boolean)) { setMessage('拼对啦！太棒了 ✨'); setScore(100); playEffect('/music/胜利.mp3'); advanceTimer.current = window.setTimeout(next, 800); } };
  return <div className="game-panel spelling-game"><div className="game-panel-head"><div><span className="eyebrow">拼写大师 · {wordIndex + 1}/{words.length}</span><h2>把字母拖到叶片上</h2></div><button className="audio-button" type="button" onClick={playSpellingAudio} aria-label="播放拼读音频">🔊</button></div><div className="spelling-visual"><button className="game-word-image" type="button" onClick={playSpellingAudio}><img src={word.image} alt={word.word} /><small>点击图片听单词</small></button><div className="leaf-board">{word.spelling.map((part, i) => <button className={draggedIndex === i ? 'is-dragging' : ''} draggable={!placed[i]} disabled={Boolean(placed[i])} onDragStart={(event) => handleDragStart(event, i)} onDragEnd={() => { setDraggedIndex(null); setDropTarget(null); }} key={`${part}-${i}`}>{part}</button>)}</div></div><div className="letter-tray">{word.spelling.map((_, i) => <span className={`${placed[i] ? 'is-filled' : ''} ${dropTarget === i ? 'is-drop-target' : ''}`} onDragOver={(event) => { if (!placed[i]) { event.preventDefault(); event.dataTransfer.dropEffect = 'move'; } }} onDragEnter={() => !placed[i] && setDropTarget(i)} onDragLeave={() => setDropTarget(null)} onDrop={(event) => handleDrop(event, i)} key={i}>{placed[i] || '·'}</span>)}</div><div className="game-actions"><button className="secondary-button" onClick={reset}>重置</button>{message && <button className="secondary-button" onClick={next}>下一词</button>}</div>{message && <p className="game-message">{message}</p>}</div>;
}

function MatchGame() {
  const setScore = useLearningStore((state) => state.setMatchingScore); const [selected, setSelected] = useState(null); const [matched, setMatched] = useState([]); const [message, setMessage] = useState('');
  const choose = (word) => { if (!selected || matched.includes(word.word)) return; if (selected === word.word) { const next = [...matched, word.word]; setMatched(next); setMessage('配对正确！'); if (next.length === words.length) setScore(calculateMatchScore(next.length, words.length)); } else setMessage('再想一想，这不是它'); setSelected(null); };
  return <div className="game-panel match-game"><div className="game-panel-head"><div><span className="eyebrow">词汇大闯关 · 5 题</span><h2>把单词送到对应的水果</h2></div><span className="progress">{matched.length} / {words.length}</span></div><p className="game-instruction">先点击左侧单词，再点击右侧图片完成配对。</p><div className="match-board"><div className="match-words">{words.map((word) => <button className={selected === word.word ? 'match-word active' : 'match-word'} disabled={matched.includes(word.word)} onClick={() => setSelected(word.word)} key={word.word}>{word.word}</button>)}</div><div className="match-images">{words.map((word) => <button className={matched.includes(word.word) ? 'match-image matched' : 'match-image'} onClick={() => choose(word)} key={word.word}><img src={word.image} alt={word.word} /><b>{matched.includes(word.word) ? '✓ ' : ''}{word.word}</b></button>)}</div></div>{message && <p className="game-message">{matched.length === words.length ? '全部配对成功，太厉害了！🎉' : message}</p>}</div>;
}

export function VocabularyPage() {
  const [tab, setTab] = useState('overview'); const [reviewMode, setReviewMode] = useState(false);
  const changeMode = (value) => { setReviewMode(value); setTab(value ? 'review' : 'overview'); };
  return <div className="vocab-page"><div className="vocab-head"><div><span className="eyebrow">词句宝库</span><h1>{tabs.find((item) => item.id === tab)?.label}</h1></div><div className="subnav">{tabs.map((item) => <button className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)} key={item.id}>{item.label}</button>)}</div></div>{tab === 'spelling' ? <SpellingGame /> : tab === 'match' ? <MatchGame /> : <VocabularyOverview reviewMode={tab === 'review' || reviewMode} onModeChange={changeMode} onChallenge={() => setTab('match')} />}</div>;
}
