import { useEffect, useRef, useState } from 'react';
import { lessonWords, words } from '../../data/lesson';
import { useLearningStore } from '../../store/useLearningStore';
import { canPlaceSpellingPart, calculateMatchScore, findSpellingDropTarget, isVocabularyMatch, shuffleVocabularyItems } from './vocabularyLogic';
import './vocabulary.css';
import './spellingDrag.css';

const tabs = [{ id: 'overview', label: '课课清' }, { id: 'review', label: '滚动复习' }, { id: 'match', label: '词汇大闯关' }];
const overviewWords = lessonWords.map(({ word }) => word);
export const playLessonAudio = (audioPath) => { const audio = new Audio(audioPath); void audio.play(); };

function VocabularyOverview({ reviewMode, onModeChange, onChallenge }) {
  const [selected, setSelected] = useState(0); const current = lessonWords[selected];
  return <section className="vocab-overview lesson-clear"><div className="overview-stats"><span>（用户名）</span><span>学习时长：50 min</span><span>积分：120</span><span>积分商城</span></div><div className="overview-tabs"><button className={!reviewMode ? 'active' : ''} onClick={() => onModeChange(false)}>课课清</button><button className={reviewMode ? 'active' : ''} onClick={() => onModeChange(true)}>滚动复习</button></div>{reviewMode ? <div className="rolling-grid">{overviewWords.map((item) => <button className="overview-word" key={item}>{item}</button>)}</div> : <div className="lesson-board"><aside className="lesson-word-list">{lessonWords.map((item, index) => <button className={selected === index ? 'selected' : ''} onClick={() => setSelected(index)} key={item.word}>{item.word}</button>)}<button className="challenge-button" onClick={onChallenge}>拼写大师</button></aside><article className="lesson-detail"><div className="detail-copy"><h2>{current.word}</h2><button className="detail-audio" aria-label="播放单词发音" onClick={() => playLessonAudio(current.audio)}>🔊</button><span className="detail-phonetic">{current.phonetic}</span><p>{current.meaning}</p><div className="detail-spelling">{current.word.split('').map((letter, index) => <span key={`${letter}-${index}`}>{letter}</span>)}</div><p className="detail-sentence">{current.sentence}</p></div><div className="detail-visual"><img src={current.image} alt={current.word} /><div className="star-rating"><span>🎙️</span>{[1, 2, 3, 4, 5].map((star) => <button key={star} aria-label={`${star} 星`}>☆</button>)}</div></div><button className="detail-arrow prev" onClick={() => setSelected((selected + lessonWords.length - 1) % lessonWords.length)}>‹</button><button className="detail-arrow next" onClick={() => setSelected((selected + 1) % lessonWords.length)}>›</button></article></div>}</section>;
}

function SpellingGame() {
  const setScore = useLearningStore((state) => state.setSpellingScore); const [wordIndex, setWordIndex] = useState(0); const [placed, setPlaced] = useState([]); const [draggedIndex, setDraggedIndex] = useState(null); const [dropTarget, setDropTarget] = useState(null); const [touchDrag, setTouchDrag] = useState(null); const [message, setMessage] = useState(''); const advanceTimer = useRef(null); const word = words[wordIndex];
  const playSpellingAudio = () => { const audio = new Audio(word.audio); void audio.play(); };
  const playEffect = (audioPath) => { const audio = new Audio(audioPath); void audio.play(); };
  const reset = () => { window.clearTimeout(advanceTimer.current); setPlaced([]); setDraggedIndex(null); setDropTarget(null); setTouchDrag(null); setMessage(''); };
  const next = () => { setWordIndex((i) => (i + 1) % words.length); reset(); };
  useEffect(() => () => window.clearTimeout(advanceTimer.current), []);
  const placePart = (partIndex, targetIndex) => { if (placed[targetIndex]) return; if (!canPlaceSpellingPart(partIndex, targetIndex, word.spelling)) { playEffect('/music/失败.mp3'); return; } const nextPlaced = [...placed]; nextPlaced[targetIndex] = word.spelling[partIndex]; setPlaced(nextPlaced); if (nextPlaced.length === word.spelling.length && nextPlaced.every(Boolean)) { setMessage('拼对啦！太棒了 ✨'); setScore(100); playEffect('/music/胜利.mp3'); advanceTimer.current = window.setTimeout(next, 800); } };
  const handleDragStart = (event, partIndex) => { event.dataTransfer.setData('text/plain', String(partIndex)); event.dataTransfer.effectAllowed = 'move'; setDraggedIndex(partIndex); };
  const handleDrop = (event, targetIndex) => { event.preventDefault(); const partIndex = Number(event.dataTransfer.getData('text/plain') || draggedIndex); setDropTarget(null); setDraggedIndex(null); placePart(partIndex, targetIndex); };
  const handlePointerDown = (event, partIndex) => { if (event.pointerType !== 'touch' || placed[partIndex]) return; event.preventDefault(); event.currentTarget.setPointerCapture?.(event.pointerId); setDraggedIndex(partIndex); setTouchDrag({ partIndex, pointerId: event.pointerId, x: event.clientX, y: event.clientY }); };
  const handlePointerMove = (event) => { if (event.pointerType !== 'touch') return; setTouchDrag((current) => current?.pointerId === event.pointerId ? { ...current, x: event.clientX, y: event.clientY } : current); };
  const handlePointerEnd = (event) => { if (event.pointerType !== 'touch' || touchDrag?.pointerId !== event.pointerId) return; event.currentTarget.releasePointerCapture?.(event.pointerId); const targetIndex = findSpellingDropTarget(document.elementFromPoint.bind(document), event.clientX, event.clientY); setTouchDrag(null); setDraggedIndex(null); if (targetIndex !== null) placePart(touchDrag.partIndex, targetIndex); };
  return <div className="game-panel spelling-game"><div className="game-panel-head"><div><span className="eyebrow">拼写大师 · {wordIndex + 1}/{words.length}</span><h2>把字母拖到叶片上</h2></div><button className="audio-button" type="button" onClick={playSpellingAudio} aria-label="播放拼读音频">🔊</button></div><div className="spelling-visual"><button className="game-word-image" type="button" onClick={playSpellingAudio}><img src={word.image} alt={word.word} /><small>点击图片听单词</small></button><div className="leaf-board">{word.spelling.map((part, i) => <button className={draggedIndex === i ? 'is-dragging' : ''} draggable={!placed[i]} disabled={Boolean(placed[i])} onDragStart={(event) => handleDragStart(event, i)} onDragEnd={() => { setDraggedIndex(null); setDropTarget(null); }} onPointerDown={(event) => handlePointerDown(event, i)} onPointerMove={handlePointerMove} onPointerUp={handlePointerEnd} onPointerCancel={handlePointerEnd} key={`${part}-${i}`}>{part}</button>)}</div></div><div className="letter-tray">{word.spelling.map((_, i) => <span data-spelling-target={i} className={`${placed[i] ? 'is-filled' : ''} ${dropTarget === i ? 'is-drop-target' : ''}`} onDragOver={(event) => { if (!placed[i]) { event.preventDefault(); event.dataTransfer.dropEffect = 'move'; } }} onDragEnter={() => !placed[i] && setDropTarget(i)} onDragLeave={() => setDropTarget(null)} onDrop={(event) => handleDrop(event, i)} key={i}>{placed[i] || '·'}</span>)}</div>{touchDrag && <span className="touch-drag-preview" style={{ left: touchDrag.x, top: touchDrag.y }}>{word.spelling[touchDrag.partIndex]}</span>}<div className="game-actions"><button className="secondary-button" onClick={reset}>重置</button>{message && <button className="secondary-button" onClick={next}>下一词</button>}</div>{message && <p className="game-message">{message}</p>}</div>;
}

function VocabularyChallengeLobby({ onStart }) {
  return <section className="vocabulary-challenge-lobby" data-testid="vocabulary-challenge-lobby">
    <div className="challenge-lobby-stats"><span>（用户名）</span><span>学习时长：50 min</span><span>积分：120</span><span>积分商城</span></div>
    <div className="challenge-lobby-modes"><button className="active" type="button">课课清</button><button type="button">滚动复习</button></div>
    <div className="challenge-lobby-card"><p className="challenge-lobby-kicker">Color Play · L1</p><h2>颜色词汇小天地</h2><div className="challenge-lobby-words">{lessonWords.map((item) => <button type="button" key={item.word} onClick={() => playLessonAudio(item.audio)}>{item.word}</button>)}</div><button className="challenge-lobby-start" type="button" onClick={onStart}>开始词汇大闯关</button></div>
  </section>;
}

function MatchGame() {
  const setScore = useLearningStore((state) => state.setMatchingScore); const [started, setStarted] = useState(false); const [selected, setSelected] = useState(null); const [matched, setMatched] = useState([]); const [message, setMessage] = useState(''); const [touchDrag, setTouchDrag] = useState(null);
  const completeMatch = (word, carriageIndex) => { if (!word || matched.includes(word)) return; const expectedWord = lessonWords[carriageIndex]?.word; if (word === expectedWord) { const next = [...matched, word]; setMatched(next); setMessage('放对啦！'); if (next.length === lessonWords.length) setScore(calculateMatchScore(next.length, lessonWords.length)); } else setMessage('再看看顺序哦！'); setSelected(null); };
  const handlePointerDown = (event, word) => { if (event.pointerType !== 'touch' || matched.includes(word)) return; event.preventDefault(); event.currentTarget.setPointerCapture?.(event.pointerId); setTouchDrag({ word, pointerId:event.pointerId, x:event.clientX, y:event.clientY }); };
  const handlePointerMove = (event) => { if (event.pointerType === 'touch') setTouchDrag((current) => current?.pointerId === event.pointerId ? { ...current, x:event.clientX, y:event.clientY } : current); };
  const handlePointerEnd = (event) => { if (event.pointerType !== 'touch' || touchDrag?.pointerId !== event.pointerId) return; const carriage = document.elementFromPoint(event.clientX, event.clientY)?.closest?.('[data-train-carriage]')?.dataset.trainCarriage; setTouchDrag(null); if (carriage) completeMatch(touchDrag.word, Number(carriage) - 1); };
  if (!started) return <VocabularyChallengeLobby onStart={() => setStarted(true)} />;
  return <section className="train-sort-game" data-testid="undersea-match"><p className="train-sort-instruction">按顺序将颜色图片拖到火车上。</p><div className="train-sort-cards">{lessonWords.map((item) => <button className={matched.includes(item.word) ? 'train-sort-card placed' : 'train-sort-card'} draggable={!matched.includes(item.word)} disabled={matched.includes(item.word)} onClick={() => setSelected(item.word)} onDragStart={(event) => event.dataTransfer.setData('text/plain', item.word)} onPointerDown={(event) => handlePointerDown(event, item.word)} onPointerMove={handlePointerMove} onPointerUp={handlePointerEnd} onPointerCancel={handlePointerEnd} key={item.word}><img src={item.image} alt={item.word} /></button>)}</div><div className="train-sort-track"><div className="train-engine" aria-hidden="true">🚂</div>{lessonWords.map((item, index) => <button className={matched.includes(item.word) ? 'train-carriage filled' : 'train-carriage'} data-train-carriage={index + 1} onClick={() => completeMatch(selected, index)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => completeMatch(event.dataTransfer.getData('text/plain'), index)} key={item.word}>{matched.includes(item.word) ? <img src={item.image} alt={item.word} /> : <span>{index + 1}</span>}</button>)}</div>{touchDrag && <span className="train-drag-preview" style={{left:touchDrag.x,top:touchDrag.y}}>{touchDrag.word}</span>}{message && <p className="train-sort-message">{matched.length === lessonWords.length ? '全部放对啦，火车出发！🎉' : message}</p>}</section>;
}

export function VocabularyPage() {
  const [tab, setTab] = useState('overview'); const [reviewMode, setReviewMode] = useState(false);
  const changeMode = (value) => { setReviewMode(value); setTab(value ? 'review' : 'overview'); };
  const isCourseOverview = tab === 'overview';
  const isMobileGame = tab === 'spelling' || tab === 'review';
  return <div className={`vocab-page vocab-page--storybook${isCourseOverview ? ' vocab-page--lesson-mobile' : ''}${isMobileGame ? ' vocab-page--mobile-game' : ''}`}><div className="vocab-head"><div><span className="eyebrow">词句宝库</span><h1>{tabs.find((item) => item.id === tab)?.label}</h1></div><div className="subnav">{tabs.map((item) => <button className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)} key={item.id}>{item.label}</button>)}</div></div>{tab === 'spelling' ? <SpellingGame /> : tab === 'match' ? <MatchGame /> : <VocabularyOverview reviewMode={tab === 'review' || reviewMode} onModeChange={changeMode} onChallenge={() => setTab('match')} />}</div>;
}
