import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { questions } from '../../data/lesson';
import { useLearningStore } from '../../store/useLearningStore';
import { calculateReviewScore } from './reviewLogic';
import './review.css';
import './review-position.css';
import './review-layout.css';

export function ReviewPage() {
  const unlocked = useLearningStore((state) => state.videoDone); const setScore = useLearningStore((state) => state.setReviewScore);
  const [questionIndex, setQuestionIndex] = useState(0); const [correctCount, setCorrectCount] = useState(0); const [choice, setChoice] = useState(null); const [finished, setFinished] = useState(false);
  useEffect(() => { if (!choice || questionIndex !== questions.length - 1) return undefined; const timer = window.setTimeout(() => { setScore(calculateReviewScore(correctCount + (choice === questions[questionIndex].answer ? 1 : 0), questions.length)); setFinished(true); }, 600); return () => window.clearTimeout(timer); }, [choice, questionIndex, correctCount, setScore]);
  if (!unlocked) return <div className="empty-state review-locked"><span>🔒</span><h2>完成今日视频后解锁</h2><p>先去“今日学习”认识水果朋友吧</p><Link className="primary" to="/today">去今日学习 →</Link></div>;
  if (finished) { const score = calculateReviewScore(correctCount, questions.length); return <div className="review-summary"><div className="confetti" aria-hidden="true">✦　✧　✦　✧　✦</div><div className="summary-badge">🎉</div><span className="eyebrow">复习乐园 · 完成啦</span><h1>你是水果小达人！</h1><p>今天的水果判断挑战全部完成</p><div className="summary-score"><b>{score}</b><span>分</span></div><div className="summary-stats"><span>答对 <b>{correctCount}</b> / {questions.length} 题</span><span>获得 <b>+20</b> 积分</span></div><div className="summary-actions"><button className="primary" onClick={() => { setQuestionIndex(0); setCorrectCount(0); setChoice(null); setFinished(false); }}>再玩一次</button><Link className="secondary-button" to="/vocabulary">去复习单词 →</Link></div></div>; }
  const question = questions[questionIndex]; const answer = (value) => { if (choice) return; setChoice(value); if (value === question.answer) setCorrectCount((count) => count + 1); }; const next = () => { if (questionIndex === questions.length - 1) { const finalCorrect = correctCount + (choice === question.answer ? 1 : 0); setScore(calculateReviewScore(finalCorrect, questions.length)); setFinished(true); } else { setQuestionIndex((index) => index + 1); setChoice(null); } }; const isCorrect = choice === question.answer;
  return <div className="review-experience"><div className={`review-stage ${choice ? (isCorrect ? 'has-correct' : 'has-wrong') : ''}`}><div className="prompt-strip"><div className="prompt-image"><img src={question.image} alt="题目图片" /></div><div className="prompt-copy"><span className="prompt-number">{questionIndex + 1}</span><span className="prompt-sentence">{question.sentence}</span><span className="prompt-answer">{question.answer}</span></div><div className="prompt-progress"><i style={{ width: `${((questionIndex + 1) / questions.length) * 100}%` }} /></div></div><div className="fruit-choice"><div className={`fruit-option watermelon ${choice === 'yes' ? 'picked-option' : ''}`}><button className={`answer yes ${choice === 'yes' ? 'picked' : ''}`} disabled={Boolean(choice)} onClick={() => answer('yes')} aria-label="Yes"><img src="/assets/docx/image21.png" alt="Yes 西瓜" /><span>yes</span></button>{isCorrect && choice === 'yes' && <img className="success-extra" src="/assets/docx/image23.png" alt="" aria-hidden="true" />}</div><div className={`fruit-option pineapple ${choice === 'no' ? 'picked-option' : ''}`}><button className={`answer no ${choice === 'no' ? 'picked' : ''}`} disabled={Boolean(choice)} onClick={() => answer('no')} aria-label="No"><img src="/assets/docx/image24.png" alt="No 菠萝" /><span>no</span></button>{isCorrect && choice === 'no' && <img className="success-extra" src="/assets/docx/image26.png" alt="" aria-hidden="true" />}</div></div><div className="stage-controls"><button className="audio-button" aria-label="播放句子音频">🔊</button><span>自动播放句子音频</span>{choice && <div className={isCorrect ? 'feedback good' : 'feedback bad'}><strong>{isCorrect ? '太棒了，回答正确！水果切开啦 ✨' : '再听一次，继续加油！水果抖一抖～'}</strong><button onClick={next}>{questionIndex === questions.length - 1 ? '查看结果' : '下一题'} →</button></div>}</div></div></div>;
}
